title: מתכונים משפחתיים
description: אתר מתכונים משפחתי, קריא ונוח לשימוש
url: "https://sagivba.github.io"
#baseurl: "/family_recipes"



remote_theme: "mmistakes/minimal-mistakes"

locale: he
lang: he
direction: rtl

google_analytics: G-VM0RV3BHEM


markdown: kramdown


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

collections:
  recipes:
    output: true
    permalink: /recipes/:name/
  docs:
    output: true
    permalink: /docs/:name/

defaults:
  - scope:
      path: ""
      type: recipes
    values:
      layout: recipe
  - scope:
      path: "docs"
    values:
      layout: doc
  - scope:
      path: "ingredients"
    values:
      layout: ingredient
